# Schema for the configuration files of the Weather module.
weather.settings:
  type: config_object
  label: 'Weather settings'
  mapping:
    key_weather_api:
      type: string
      label: 'Key for Weather API'

block.settings.weather_block:
  type: block_settings
  label: 'Weather block'
  mapping:
    city_weather:
      type: sequence
      label: 'Select your weather units'
