# Schema for the configuration files of the Weather module.
weather.settings:
  type: config_object
  label: 'Weather settings'
  mapping:
    example:
      type: string
      label: 'Example'

block.settings.weather_block:
  type: block_settings
  label: 'Weather block block'
  mapping:
    foo:
      type: string
      label: Foo
