# Schema for the configuration files of the exchange_rates module.
exchange_rates.settings:
  type: config_object
  label: 'Exchange rates settings'
  mapping:
    key_api:
      type: string
      label: 'Key for currency rate API'
    currencies:
      type: sequence
      label: 'Currencies that will be show'
      sequence:
        - type: string
          label: 'Currency name'
