# Schema for the configuration files of the exchange_rates module.
exchange_rates.settings:
  type: config_object
  label: 'Exchange rates settings'
  mapping:
    example:
      type: string
      label: 'Example'
