<?php

/**
 * @file
 * Primary module hooks for Weather module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function weather_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.weather':
      $output = '';
      $output .= '<h4>' . t('About') . '</h4>';
      $output .= '<p>' . t('This module show a weather in different regions.') . '</p>';
      return $output;
  }
}

/**
 * Implements hook_theme().
 */
function weather_theme($existing, $type, $theme, $path) {
  return [
    'weather_block_template' => [
      'variables' => [
        'data_weather' => [],
        'main_data_weather' => [],
      ],
    ],
  ];
}
