<?php

/**
 * @file
 * Primary module hooks for Weather module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function weather_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.weather':
      $output = '';
      $output .= '<h4>' . t('About') . '</h4>';
      $output .= '<p>' . t('This module show a weather in different regions.') . '</p>';
      return $output;
  }
}

/**
 * Implements hook_theme().
 */
function weather_theme($existing, $type, $theme, $path) {
  return [
    'weather_block_template' => [
      'variables' => [
        'data_weather' => [],
        'main_data_weather' => [],
        'lutsk_weather' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_cron().
 */
function weather_cron() {
  $city_name = \Drupal::config('weather.settings')->get('city_weather');
  $key_api_weather = \Drupal::config('weather.settings')->get('key_weather_api');
  $metric = \Drupal::config('weather.settings')->get('metric');
  $url_weather = "https://api.openweathermap.org/data/2.5/weather?q=$city_name&appid=$key_api_weather&units=$metric";
  $response = \Drupal::httpClient()->request('GET', $url_weather);
  $weather_data = $response->getBody()->getContents();
  $timestamp = \Drupal::time()->getRequestTime();
  $values = [
    'data_weather' => $city_name,
    'main_data_weather' => $weather_data,
    'time' => $timestamp,
  ];
  \Drupal::database()->update('weather_table')
    ->fields($values)
    ->condition('id', 1)
    ->execute();
}
